# THIS IS HEADING1 (H1 TAG)
## THIS IS HEADING2 (H2 TAG)
### THIS IS HEADING3 (H3 TAG)
#### THIS IS HEADING4 (H4 TAG)
##### THIS IS HEADING5 (H5 TAG)
###### THIS IS HEADING6 (H6 TAG)

# NUMPY
- NUMERICAL PYTHON
- IT IS MULTIDIMENISION 
- IT TAKES LESS TIME TO EXECUTE
- NUMERICAL OPERATION

In [1]:
import numpy as np

In [1]:
dir(np)

NameError: name 'np' is not defined

In [4]:
d1 = np.array([45,74,85,36,65,57])
d1


array([45, 74, 85, 36, 65, 57])

In [5]:
d1.shape

(6,)

In [6]:
d1.size

6

In [7]:
d1.ndim

1

In [8]:
d1

array([45, 74, 85, 36, 65, 57])

In [9]:
d1[1]

74

In [10]:
d1[2]

85

In [11]:
d1[0:3]

array([45, 74, 85])

In [12]:
np.array(["aditya",517,"CSE","A",67.82])
data

NameError: name 'data' is not defined

In [13]:
data = np.array(["aditya",517,"CSE","A",67.82])
data

array(['aditya', '517', 'CSE', 'A', '67.82'], dtype='<U6')

In [15]:
import time

start_time = time.time()
list1 = [x for x in range(1,100000)]
list2 = [y for y in range(1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()

print("Time taken by list concept",end_time-start_time)

Time taken by list concept 0.0354306697845459


In [53]:
import time

start_time1 = time.time()

ar1 = np.array(list1)
ar2 = np.array(list2)

arl*ar2

end_time1 = time.time()

print("Time taken by numpy is:",end_time1-start_time1)


SyntaxError: invalid syntax (<ipython-input-53-f3211060b205>, line 12)

## array -- 
## array -- 0.0119

In [32]:
d2[2]

array([78, 90, 66])

In [20]:
# 2-D Array Declaration
d2 = np.array([[45,74,36],[96,87,69],[78,90,66]])
d2

array([[45, 74, 36],
       [96, 87, 69],
       [78, 90, 66]])

In [33]:
d2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [22]:
d2.shape

(3, 3)

In [23]:
d2.size

9

In [30]:
d2.ndim

2

In [34]:
d2[0,2]

36

In [37]:
d2[1,0]

96

In [38]:
d2[1].max()

96

In [39]:
np.max(d2[1])

96

In [40]:
d2[:,2]

array([36, 69, 66])

In [41]:
d2[:,1].max()

90

In [42]:
d2[:,1].min()

74

In [43]:
d2[:,2].min()

36

In [44]:
d2[0].sum()

155

In [46]:
d2.sum()

641

In [47]:
d2.sum(axis=0)

array([219, 251, 171])

In [48]:
d2

array([[45, 74, 36],
       [96, 87, 69],
       [78, 90, 66]])

In [49]:
d2.sum(axis=1)

array([155, 252, 234])

In [51]:
d3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
d3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
d3[0,0]

array([1, 2, 3])

In [56]:
d3[0,0,1]

2

## arrange()

In [57]:
for i in range(1,11):
    print(i,end = "  ")

1  2  3  4  5  6  7  8  9  10  

In [59]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
for i in range(1,10,0.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [63]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [64]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [70]:
# zeos matrix
print(np.zeros([10,20]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [71]:
# zeos matrix
print(np.zeros([2,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [72]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [76]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.tile(10,[4,4])

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [78]:
d21 = np.array([[14,25,36,41,52],
         [24,51,35,15,16]])
d21

array([[14, 25, 36, 41, 52],
       [24, 51, 35, 15, 16]])

In [79]:
add_marks = np.tile(5,[2,5])
add_marks


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [80]:
final_marks = d21+add_marks
final_marks

array([[19, 30, 41, 46, 57],
       [29, 56, 40, 20, 21]])

In [81]:
mat = np.array([[1,10,20],[2,20,30],[3,45,55]])
mat

array([[ 1, 10, 20],
       [ 2, 20, 30],
       [ 3, 45, 55]])

In [82]:
np.linalg.inv(mat)

array([[-1.66666667,  2.33333333, -0.66666667],
       [-0.13333333, -0.03333333,  0.06666667],
       [ 0.2       , -0.1       ,  0.        ]])

In [83]:
np.linalg.eig(mat)

(array([79.2418833 , -0.76390403, -2.47797927]),
 array([[-0.27476378, -0.98372828, -0.86503683],
        [-0.44175308, -0.11022856, -0.37213216],
        [-0.85402523,  0.14187439,  0.33649509]]))

## random

In [84]:
np.random.random(10)

array([0.30694662, 0.78527418, 0.7168046 , 0.97717821, 0.37848024,
       0.21287256, 0.66360398, 0.37402218, 0.84522376, 0.99569034])

In [85]:
np.random.random(1,100)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [86]:
np.random.randint(10)

7

In [87]:
np.random.randint(10)

6

In [88]:
np.random.randint(10,20)

12

In [90]:
np.random.randint(10,20)

15

In [91]:
np.random.randint(10,20,30)

array([15, 18, 13, 19, 12, 18, 17, 10, 18, 16, 16, 10, 16, 12, 10, 10, 19,
       13, 17, 17, 17, 19, 19, 16, 10, 16, 13, 17, 13, 14])

In [92]:
np.random.randint(10,25,[4,6])

array([[23, 14, 16, 18, 24, 17],
       [11, 10, 17, 11, 20, 24],
       [19, 17, 19, 24, 19, 21],
       [20, 12, 23, 22, 19, 18]])

In [94]:
np.random.rand(10)

array([0.76319958, 0.97787356, 0.65156733, 0.23286166, 0.4621718 ,
       0.48848566, 0.04217603, 0.08665263, 0.52730537, 0.43181553])

In [95]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [ ]:
np.arange()